people/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    
    url(r'^edit/(?P<username>[\w.@+-]+)/$', views.EditProfile, name="edit-profile"),
    
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserProfile, name="user-profile"),
    
    
    
    
    
    ]

tinventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from tinventory.core import views as core_views
from people import views as people_views
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

urlpatterns = [
    
    url(r'^$', core_views.HomePage.as_view(), name='home'),
    
    url(r'^admin/', admin.site.urls),
    
    url(r'^transformations/', include('transformations.urls')),
    
    url(r'^resources/', include('resources.urls')),
    
    url(r'^topics/', include('topics.urls')),
    
    url(r'^users/', include('people.urls')),
    
    url(r'^login/$', auth_views.login, name='login'),
    
    url(r'^logout/$', auth_views.logout, name='logout'),
    
    url(r'^signup/$', core_views.signup, name='signup'),
    
    url(r'^feed/$', people_views.ActivityFeed.as_view(), name='activity-feed'),
    
    url(r'^leaderboard/$', people_views.Leaderboard, name='leaderboard'),
    
    url(r'^feedback/', core_views.FeedbackForm.as_view(), name='feedback'),
    
    url(r'^search/', core_views.SearchResults.as_view(), name='search'),
    
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^terms/accept/', core_views.MyAcceptTerms.as_view(), name='accept-terms'),
    url(r'^terms/', core_views.MyViewTerms.as_view(), name='terms'),
    
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^', include(wagtail_urls)),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

people/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
import os
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

# PROFILE ------------

class Profile(models.Model):

    def get_upload_path(instance, filename):
        return os.path.join('users', timezone.now().strftime("%y-%m-%d"), filename)
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    ministry = models.ForeignKey('transformations.Ministry', blank=True, null=True, related_name='profiles')
    role = models.CharField(max_length=200, blank=True, null=True)
    profile_picture = models.ImageField(upload_to=get_upload_path, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(null=True, blank=True)
    
    def get_absolute_url(self):
        return "/users/%s" % (self.user.username)
        
    def __str__(self):
        return "Profile for %s" % (self.user.get_full_name())
    
# ACTIVITY STREAM -------------

class Action(models.Model):
    user = models.ForeignKey(User, related_name='actions', db_index=True)
    verb = models.CharField(max_length=255)
    target_type = models.ForeignKey(ContentType, blank=True, null=True, related_name='target_obj')
    target_id = models.PositiveIntegerField(null=True, blank=True, db_index=True)
    target = GenericForeignKey('target_type', 'target_id')
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        ordering=('-created',)
        
    def __str__(self):
        return '%s - %s %s %s \'%s\'.' % (self.created.strftime('%m%d%y-%H%M'), self.user.get_full_name(), self.verb, self.target_type, self.target)

people/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.contrib.auth.models import User
from .models import Profile

class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
    
class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['ministry', 'role', 'profile_picture']

tinventory/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import EmailValidator
from people.models import Profile

# much of this authentication stuff taken from https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        
    def __init__(self,*args,**kwargs):
        super(SignUpForm,self).__init__(*args,**kwargs)
        for x in self.fields:
            self.fields[x].required = True
            self.fields[x].help_text = None

    def clean_email(self):
        email = self.cleaned_data['email']
        (first, second,) = email.split("@")
        (domain, exn,) = second.split(".")
        if domain != "ontario" or exn != 'ca':
            raise forms.ValidationError("Domain must be 'ontario.ca'")
        return email 
        
class ProfileSignupSubform(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['ministry','role','profile_picture']
        
    def __init__(self,*args,**kwargs):
        super(ProfileSignupSubform,self).__init__(*args,**kwargs)
        for x in self.fields:
            self.fields[x].required = True
            self.fields[x].help_text = None
        self.fields['profile_picture'].required = False
        self.fields['profile_picture'].help_text="(Optional)"
        


class FeedbackForm(forms.Form):
    
    FEEDBACK_CATEGORIES = (
        ('Bug','Bug Report: Something\'s not working.'),
        ('PainPoint','Pain Point: It\'s working, but not the way I would like.'),
        ('UserStory','User Story: As a ___ I would like to ___ so I can ___.'),
        ('OtherIdea','Other Feature Idea or Suggestion'),
        ('Compliment','Compliments: Something you particularly like.'),
        ('Question','Questions: Just wondering...'),
        ('other','Other'),
    )
    
    feedback_category = forms.ChoiceField(choices=FEEDBACK_CATEGORIES)
    subject = forms.CharField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

people/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Profile, Action
from django.contrib.auth.models import User
from django.utils import timezone
from .forms import UserForm, ProfileForm
from django.urls import reverse
from django.contrib import messages
from .helpers import create_action
from django.views import generic
from django.conf import settings
from django.db.models import Sum, Count, Avg
from resources.models import Resource, Review
from django.contrib.auth import get_user_model
from transformations.models import Transformation, Ministry

def UserProfile(request, username):
    
    this_user = get_object_or_404(User, username=username)
    
    try:
        my_profile = Profile.objects.get(user=this_user)
        
    except:
        new_profile = Profile.objects.create(user=this_user)
        new_profile.last_login = timezone.now()
        new_profile.date_joined = timezone.now()
        new_profile.save()
    
    return render(request, 'people/profile.html', {'user':this_user})
    
def EditProfile(request, username):
    
    this_user = get_object_or_404(User, username=username)
    
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=this_user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=this_user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request,'Your profile has been updated.')
            create_action(request.user, 'updated', Profile.objects.get(user=this_user))
            return redirect(reverse('user-profile', kwargs={'username':username}))
            
    else:
        
        user_form = UserForm(instance=this_user)
        profile_form = ProfileForm(instance=this_user.profile)
        context = {
            'user':this_user,
            'user_form':user_form,
            'profile_form':profile_form,
            }
    
    return render(request,'people/edit_profile.html', context)
    
class ActivityFeed(generic.ListView):
    model=Action
    template_name='people/activity_feed.html'
    
class Standings(object):
    
    def __init__(self,title,xaxis,measure,queryset=None, model=None, func=None, measure_var=None):
        self.title=title
        self.xaxis=xaxis
        self.measure=measure
        self.queryset = model.objects.annotate(number=func(measure_var)).filter(number__gt=0).order_by('-number')[:5]

def Leaderboard(request):
    
    User = get_user_model()
    
    leaderboards = [
        
        Standings(
            title='Most Active Users',
            xaxis='User',
            measure='Actions',
            model=User,
            func=Count,
            measure_var='actions'
            ),
                        
        Standings(
            title='Users with most Stars',
            xaxis='User',
            measure='Stars',
            model=User,
            func=Sum,
            measure_var='resources_created__reviews__rating'
            ),
        
        Standings(
            title='Top Resources',
            xaxis='Resource',
            measure='Stars',
            model=Resource,
            func=Sum,
            measure_var='reviews__rating'
            ),
            
        Standings(
            title='Highest Avg Rating',
            xaxis='Resource',
            measure='Stars',
            model=Resource,
            func=Avg,
            measure_var='reviews__rating'
            ),
                    
        Standings(
            title='Top Reviewers',
            xaxis='User',
            measure='Reviews',
            model=User,
            func=Count,
            measure_var='reviews'
            ),
            
        Standings(
            title='Transformations with Most Resources',
            xaxis='Transformation',
            measure='Resources',
            model=Transformation,
            func=Count,
            measure_var='resources'
            ),
            
        Standings(
            title='Ministry with most Transformations',
            xaxis='Ministry',
            measure='Transformations',
            model=Ministry,
            func=Count,
            measure_var='transformations'
            ),
            
        Standings(
            title='Ministry with most Users',
            xaxis='Ministry',
            measure='Users',
            model=Ministry,
            func=Count,
            measure_var='profiles'
            ),
    ]
    
    context = {'leaderboards':leaderboards}
    
    return render(request,'people/leaderboard.html',context)
    

tinventory/core/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from tinventory.core.forms import SignUpForm, ProfileSignupSubform, FeedbackForm
from stronghold.decorators import public
from people.helpers import create_action
from people.models import Profile, Action
from transformations.models import Transformation
from sitepages.models import MiniFeedPage
from resources.models import Resource
from topics.models import Topic
from django.utils import timezone
from django.db import Error
from django.views.generic import TemplateView, FormView, DetailView
from django.core.mail import EmailMessage
from django.template.loader import get_template
from termsandconditions.decorators import terms_required
from termsandconditions.views import AcceptTermsView
from termsandconditions.models import TermsAndConditions
from django.utils.decorators import method_decorator
from django.contrib import messages

@public
def signup(request):
    if request.method == 'POST':
        
        form = SignUpForm(request.POST)
        subform = ProfileSignupSubform(request.POST,request.FILES)
        
        if form.is_valid() and subform.is_valid():
            
            # Save the new user
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            
            # Create and populate the profile
            new_profile = Profile.objects.create(user=user)
            new_profile.ministry = subform.cleaned_data['ministry']
            new_profile.role = subform.cleaned_data['role']
            new_profile.profile_picture = subform.cleaned_data['profile_picture']
            new_profile.last_login = timezone.now()
            new_profile.save()
                
            # Note success and log the user in.
            create_action(user,'joined the site')
            login(request, user)
            return redirect('home')
            
    else:
        
        form = SignUpForm()
        subform = ProfileSignupSubform()
        
    return render(request, 'registration/signup.html', {'form': form, 'subform':subform,})

class HomePage(TemplateView):
    
    template_name = 'core/homepage.html'
    
    def get_context_data(self, **kwargs):
        my_context = {
            'transformation_count':Transformation.objects.count(),
            'resources_count':Resource.objects.count(),
            'topics_count':Topic.objects.exclude(level=0).count(),
            'users_count':Profile.objects.count(),
            'recent_actions':Action.objects.exclude(target_type=None)[:5],
            'site_updates_page':MiniFeedPage.objects.get(slug='site-updates')
        }
        
        context = super(TemplateView,self).get_context_data(**kwargs)
        context.update(my_context)
        
        return context
        
    @method_decorator(terms_required)
    def dispatch(self, request, *args, **kwargs):
        return super(HomePage, self).dispatch(request, *args, **kwargs)
        
class MyAcceptTerms(AcceptTermsView):
    template_name = 'registration/accept_terms.html'
    
class MyViewTerms(DetailView):
    template_name = 'registration/view_terms.html'
    context_object_name = 'terms'
    
    def get_object(self,**kwargs):
        obj = TermsAndConditions.objects.latest('date_active').get_active()
        return obj
        
    
    
class FeedbackForm(FormView):
    
    form_class = FeedbackForm
    template_name = 'core/feedback_form.html'

    def form_valid(self,form):
        
        template = get_template('core/feedback_template.html')
        context = {
            'feedback_category': self.request.POST.get('feedback_category', ''),
            'content': self.request.POST.get('content', ''),
            'user': self.request.user.email,
            'path': self.request.META.get('HTTP_REFERER'),
        }
        
        content = template.render(context)

        email = EmailMessage(
            '%s #%s' % (self.request.POST.get('subject'), context['feedback_category']),
            content,
            "T-Repo" +'',
            ['paulkugelmass+tepvl3fctswujtfshyjt@boards.trello.com'],
        )
        
        email.send()
        messages.success(self.request,'You are LITERALLY the best. Thanks for sharing your feedback!')
        
        return redirect('home')
        
class SearchResults(TemplateView):
    template_name='core/search.html'

tinventory/templates/people/activity_feed.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}
{% load hyperlink_list %}

{% block title %}Activities{% endblock %}

{% block header %}All Activities{% endblock %}

{% block content %}

     <div class="row">
          <div class="col-md-12">
               <table class="table table-striped table-responsive table-condensed">
                    <tr>
                         <th>Time</th>
                         <th>User</th>
                         <th>Activity</th>
                    </tr>
                    {% for activity in action_list %}
                    <tr>
                         <td>{{activity.created}}</td>
                         <td><a href="{{activity.user.profile.get_absolute_url}}">{{activity.user}}</a></td>
                         <td>{{activity.verb|capfirst}}
                         {% if activity.target %}
                              {{activity.target.type}} 
                              <a href="{{activity.target.get_absolute_url}}">'{{activity.target}}'</a>
                          {% endif %}
                         </td>
                    </tr>
                    {% endfor %}
               </table>

               
               
          </div>
          
          
     </div>

{% endblock %}

tinventory/templates/people/edit_profile.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}

{% block title %}Edit Profile{% endblock %}
{% block header %}Edit Profile{% endblock %}

{% block content %}
{% load widget_tweaks %}

     <form method="POST" action="" class="form-group form-horizontal" enctype="multipart/form-data">
     {% csrf_token %}
     
     <div class="row">
          <div class="col-md-12">
          
          <div class="row">
               <div class="col-md-12">
                    
                    {% if form.non_field_errors %}
                         <div class="alert alert-info"> 
                              {{form.non_field_errors|join:", "}}
                         </div>
                    {% endif %}
                    
                    <table class="table table-striped align-middle">
                         {% for field in user_form %}
                         <tr>
                              <th class="col-md-2">
                                   {{field.label}}
                                   {% if field.help_text %}
                                        <br/><span class="small info">{{field.help_text }}</span>
                                   {% endif %}
                              </th>
                              <td class="col-md-10">
                                   {% if field.errors %}
                                        {{ field.errors }}
                                   {% endif %}
                                   {{field|add_class:"form-control"}}
                              </td>
                         </tr>
                         {% endfor %}
                         {% for field in profile_form %}
                         <tr>
                              <th class="col-md-2">
                                   {{field.label}}
                                   {% if field.help_text %}
                                        <br/><span class="small info">{{field.help_text }}</span>
                                   {% endif %}
                              </th>
                              <td class="col-md-10">
                                   {% if field.errors %}
                                        {{ field.errors }}
                                   {% endif %}
                                   {{field|add_class:"form-control"}}
                              </td>
                         </tr>
                         {% endfor %}
                    </table>
               
               </div>
               </div>
          </div>
          
{% include 'core/bottom_buttons.html' %}    
               
{% endblock %}

tinventory/templates/people/leaderboard.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}
{% load hyperlink_list %}

{% block title %}Leaderboard{% endblock %}

{% block header %}Site Leaderboards{% endblock %}

{% block content %}

{% for board in leaderboards %}
    {% cycle '<div class="row"><div class="col-md-4">' '<div class="col-md-4">' '<div class="col-md-4">' %}
        <h4>{{board.title}}</h4>
        <table class="table table-striped table-hover table-condensed">
            <tr>
                <th>{{board.xaxis}}</th>
                <th>{{board.measure}}</th>
            </tr>
            {% for x in board.queryset %}
                <tr>
                    <td>{{forloop.counter}}.  <a href="{{x.get_absolute_url}}">{{x}}</a></td>
                    <td>{{x.number}}</td>
                </tr>
            {% empty %}
                <div class="panel panel-default">None yet.</div>
            {% endfor %}
        </table>
    {% cycle '</div>' '</div>' '</div></div>' %}
{% endfor %}
            


               
               
          </div>
          
          
     </div>

{% endblock %}

tinventory/templates/people/profile.html
{% extends "core/base_page.html" %}
{% load humanize %}

{% block title %} 
     Profile - {{user.get_full_name}}
{% endblock %}

{% block header %}

    {{user.get_full_name|default:user.username}}<small> (User)</small>
     
{% endblock %}

{% if user == request.user %}
    
    {% block item-buttons %}
    
        <a class="button-flex" href="{% url 'edit-profile' username=user.username %}" data-toggle="tooltip" title="Edit Profile">
        <span class="glyphicon glyphicon-pencil"></span> Edit Your Profile
        </a>
        
    {% endblock %}
    
{% endif %}

{% block content %}


     
     <div class="row">
         
         {% if user.profile.profile_picture %}
         
             <div class="col-md-3">
                 
                 <img src="{{user.profile.profile_picture.url}}" class="img-responsive img-thumbnail" alt="{{user.get_full_name}}">
                 
            </div>
                 
            <div class="col-md-9">
                 
               <div class="row">
                
        {% else %}
        
            <div class="col-md-12">
                
        {% endif %}
        
             
        
               <table class="table table-striped table-condensed align-middle">
                    <tr>
                         <th class="col-md-2">User</th>
                         <td>{{user.get_full_name}} ({{user.username}})</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Ministry</th>
                         <td>{{user.profile.ministry}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Role</th>
                         <td>{{user.profile.role}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Email</th>
                         <td>{{user.email|urlize}}</td>
                    </tr>                    
                    <tr>
                         <th class="col-md-2">Joined</th>
                         <td>{{user.profile.date_created|date:"M j, Y"}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Last Visited</th>
                         <td>{{user.profile.last_login|naturaltime|capfirst}}</td>
                    </tr>
               </table>
               </div>
               </div>
     
     
     {% if user.actions.all %}
     <div class='row'>
          <div class='col-md-12'>
               <h4>Recent Contributions <small>(Last 10)</small></h4>
               
               <table class="table table-condensed table-striped">
                    
                    <tr>
                         <th>When</th>
                         <th>Activity</th>
                    </tr>
                    
               {% for action in user.actions.all|slice:'10' %}
               
                    <tr>
                         <td class="col-md-2">{{action.created|naturalday|capfirst}}</td>
                         <td>
                              {{action.verb|capfirst}} {{action.target.type}} 
                              {% if action.target %}
                                  <a href="{{action.target.get_absolute_url}}">'{{action.target}}'</a>
                             {% endif %}
                         </td>
                    </tr>
                    
               {% endfor %}
               
               </ul>
          </div>
          </div>
     </div>
     {% endif %}

{% endblock %}