people/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    
    url(r'^edit/(?P<username>[\w.@+-]+)/$', views.EditProfile, name="edit-profile"),
    
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserProfile, name="user-profile"),
    
    
    
    
    
    ]

tinventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from tinventory.core import views as core_views
from people import views as people_views
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

urlpatterns = [
    
    url(r'^$', core_views.HomePage.as_view(), name='home'),
    
    url(r'^admin/', admin.site.urls),
    
    url(r'^transformations/', include('transformations.urls')),
    
    url(r'^resources/', include('resources.urls')),
    
    url(r'^topics/', include('topics.urls')),
    
    url(r'^users/', include('people.urls')),
    
    url(r'^login/$', auth_views.login, name='login'),
    
    url(r'^logout/$', auth_views.logout, name='logout'),
    
    url(r'^signup/$', core_views.signup, name='signup'),
    
    url(r'^feed/$', people_views.ActivityFeed.as_view(), name='activity-feed'),
    
    url(r'^leaderboard/$', people_views.Leaderboard, name='leaderboard'),
    
    url(r'^feedback/', core_views.FeedbackForm.as_view(), name='feedback'),
    
    url(r'^search/', core_views.SearchResults.as_view(), name='search'),
    
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^terms/accept/', core_views.MyAcceptTerms.as_view(), name='accept-terms'),
    url(r'^terms/', core_views.MyViewTerms.as_view(), name='terms'),
    
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^', include(wagtail_urls)),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

topics/urls.py
from django.conf.urls import url, include
from . import views
from resources.views import AddResource

urlpatterns = [
     
     url(r'^$', views.TopicsList.as_view(), name='topics'),
     
     url(r'(?P<slug>[-\w]+)/add(?P<type>[a-z]+)/$', AddResource, {'base':'topic'}, name='resource-add-topic'),
     
     url(r'(?P<slug>[-\w]+)/$', views.TopicDetail, name='topic-detail'),
     
     #url(r'add(?P<type>[a-z]+)/$', AddResource, {'base':'topic'}, name='resource-add-topic-base'),

     ]

topics/models.py
from django.db import models
from mptt.models import TreeForeignKey, MPTTModel
from autoslug import AutoSlugField
from django.urls import reverse 
from functools import reduce
import operator

class Topic(MPTTModel):
    title = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='subtopics', db_index=True)
    description = models.CharField(max_length=240,blank=True)
    slug = AutoSlugField(populate_from='title')
    
    class MPTTMeta:
        order_insertion_by = ['title']
        
    def __str__(self):
        return self.title
        
    # def resources(self):
    #     return self.resource_set.all()
        
    def resourcefamily(self):
        
        from resources.models import Resource
        
        tree = self.get_descendants(include_self=True)
        q_list = [Resource.objects.filter(topics=leaf) for leaf in tree ]
        
        # Turns list of querysets into a bunch of queries connected by 'OR'
        combined_q = q_list.pop()
        for q in q_list:
            combined_q |= q
            
        return combined_q.distinct()

    def get_absolute_url(self):
        return reverse('topic-detail', args=[str(self.slug)])
        
        
    

tinventory/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import EmailValidator
from people.models import Profile

# much of this authentication stuff taken from https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        
    def __init__(self,*args,**kwargs):
        super(SignUpForm,self).__init__(*args,**kwargs)
        for x in self.fields:
            self.fields[x].required = True
            self.fields[x].help_text = None

    def clean_email(self):
        email = self.cleaned_data['email']
        (first, second,) = email.split("@")
        (domain, exn,) = second.split(".")
        if domain != "ontario" or exn != 'ca':
            raise forms.ValidationError("Domain must be 'ontario.ca'")
        return email 
        
class ProfileSignupSubform(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['ministry','role','profile_picture']
        
    def __init__(self,*args,**kwargs):
        super(ProfileSignupSubform,self).__init__(*args,**kwargs)
        for x in self.fields:
            self.fields[x].required = True
            self.fields[x].help_text = None
        self.fields['profile_picture'].required = False
        self.fields['profile_picture'].help_text="(Optional)"
        


class FeedbackForm(forms.Form):
    
    FEEDBACK_CATEGORIES = (
        ('Bug','Bug Report: Something\'s not working.'),
        ('PainPoint','Pain Point: It\'s working, but not the way I would like.'),
        ('UserStory','User Story: As a ___ I would like to ___ so I can ___.'),
        ('OtherIdea','Other Feature Idea or Suggestion'),
        ('Compliment','Compliments: Something you particularly like.'),
        ('Question','Questions: Just wondering...'),
        ('other','Other'),
    )
    
    feedback_category = forms.ChoiceField(choices=FEEDBACK_CATEGORIES)
    subject = forms.CharField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

tinventory/core/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from tinventory.core.forms import SignUpForm, ProfileSignupSubform, FeedbackForm
from stronghold.decorators import public
from people.helpers import create_action
from people.models import Profile, Action
from transformations.models import Transformation
from sitepages.models import MiniFeedPage
from resources.models import Resource
from topics.models import Topic
from django.utils import timezone
from django.db import Error
from django.views.generic import TemplateView, FormView, DetailView
from django.core.mail import EmailMessage
from django.template.loader import get_template
from termsandconditions.decorators import terms_required
from termsandconditions.views import AcceptTermsView
from termsandconditions.models import TermsAndConditions
from django.utils.decorators import method_decorator
from django.contrib import messages

@public
def signup(request):
    if request.method == 'POST':
        
        form = SignUpForm(request.POST)
        subform = ProfileSignupSubform(request.POST,request.FILES)
        
        if form.is_valid() and subform.is_valid():
            
            # Save the new user
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            
            # Create and populate the profile
            new_profile = Profile.objects.create(user=user)
            new_profile.ministry = subform.cleaned_data['ministry']
            new_profile.role = subform.cleaned_data['role']
            new_profile.profile_picture = subform.cleaned_data['profile_picture']
            new_profile.last_login = timezone.now()
            new_profile.save()
                
            # Note success and log the user in.
            create_action(user,'joined the site')
            login(request, user)
            return redirect('home')
            
    else:
        
        form = SignUpForm()
        subform = ProfileSignupSubform()
        
    return render(request, 'registration/signup.html', {'form': form, 'subform':subform,})

class HomePage(TemplateView):
    
    template_name = 'core/homepage.html'
    
    def get_context_data(self, **kwargs):
        my_context = {
            'transformation_count':Transformation.objects.count(),
            'resources_count':Resource.objects.count(),
            'topics_count':Topic.objects.exclude(level=0).count(),
            'users_count':Profile.objects.count(),
            'recent_actions':Action.objects.exclude(target_type=None)[:5],
            'site_updates_page':MiniFeedPage.objects.get(slug='site-updates')
        }
        
        context = super(TemplateView,self).get_context_data(**kwargs)
        context.update(my_context)
        
        return context
        
    @method_decorator(terms_required)
    def dispatch(self, request, *args, **kwargs):
        return super(HomePage, self).dispatch(request, *args, **kwargs)
        
class MyAcceptTerms(AcceptTermsView):
    template_name = 'registration/accept_terms.html'
    
class MyViewTerms(DetailView):
    template_name = 'registration/view_terms.html'
    context_object_name = 'terms'
    
    def get_object(self,**kwargs):
        obj = TermsAndConditions.objects.latest('date_active').get_active()
        return obj
        
    
    
class FeedbackForm(FormView):
    
    form_class = FeedbackForm
    template_name = 'core/feedback_form.html'

    def form_valid(self,form):
        
        template = get_template('core/feedback_template.html')
        context = {
            'feedback_category': self.request.POST.get('feedback_category', ''),
            'content': self.request.POST.get('content', ''),
            'user': self.request.user.email,
            'path': self.request.META.get('HTTP_REFERER'),
        }
        
        content = template.render(context)

        email = EmailMessage(
            '%s #%s' % (self.request.POST.get('subject'), context['feedback_category']),
            content,
            "T-Repo" +'',
            ['paulkugelmass+tepvl3fctswujtfshyjt@boards.trello.com'],
        )
        
        email.send()
        messages.success(self.request,'You are LITERALLY the best. Thanks for sharing your feedback!')
        
        return redirect('home')
        
class SearchResults(TemplateView):
    template_name='core/search.html'

topics/views.py
from django.shortcuts import render
from .models import Topic
from django.views import generic
from resources.forms import LinkForm, FileForm

class TopicsList(generic.ListView):
    model = Topic
    template_name = 'topics/topics_list.html'
    
    def get_queryset(self):
        return super(TopicsList,self).get_queryset().prefetch_related()
    
def TopicDetail(request, slug):
    
    this_topic = Topic.objects.get(slug=slug)
    
    context = {
        'topic':this_topic,
        }
        
    return render(request,'topics/topic_detail.html',context)

tinventory/templates/topics/topic_detail.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}
{% load mptt_tags %}
{% load hyperlink_list %}

{% block title %}Topics - {{topic.title}} {% endblock %}

{% block header %} 
     {{ topic.title }} 
     
     {% if topic.parent %} 
          <small> (<a href="{% url 'topic-detail' slug=topic.parent.slug %}">{{topic.parent}}</a>)</small>
     {% endif %}

{% endblock %}

{% block item-buttons %} 

     <div class="dropdown">
        <button class="button-flex-white dropdown-toggle" type="button" data-toggle="dropdown">
        <span class="glyphicon glyphicon-plus-sign"></span>  Add to This Topic
        <span class="caret"></span></button>
         
        <ul class="dropdown-menu">
            <li><a href="{% url 'resource-add-topic' type='link' slug=topic.slug %}">Add a new link</a></li>
            <li><a href="{% url 'resource-add-topic' type='file' slug=topic.slug %}">Add a new file</a></li>
            <li><a href="{% url 'resource-add-topic' type='post' slug=topic.slug %}">Add a new post</a></li>
        </ul>
        
     </div>
     
{% endblock %}

{% block content %}

     <div class="row">
          <div class="col-md-12">
               <table class="table table-striped">
                    {% if topic.description %}
                    <tr>
                         <th class="col-md-1">Description:</th>
                         <td>{{topic.description}}</td>
                    </tr>
                    {% endif %}
                    {% if topic.get_descendants %}
                         <tr>
                              <th class="col-md-1">Subtopics:</th>
                              <td>{% autoescape off %}{{topic.get_descendants|hyperlink_list:"slug"}}{% endautoescape %}</td>
                         </tr>
                    {% endif %}
               </table>
          </div>
     </div>
     
     {% include 'resources/resource_table_include.html' with resource_list=topic.resourcefamily %}
     

{% endblock %}

tinventory/templates/topics/topics_list.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}
{% load mptt_tags %}

{% block title %}Transformation Topics {% endblock %}

{% block header %}Transformation Topics{% endblock %}

{% block item-buttons %}{% endblock %}

{% block content %}

    <div id="page-cards-flex">

    {% for node in topic_list %}
    
        {% if node.is_root_node %}

            <div class="topic-list">
                
                <h3>{{node.title}}</h3>
                
                {% for topic in node.get_children %}
                    
                    <div class="topic-card">
                        
                        <a href="{% url 'topic-detail' slug=topic.slug %}"><h4>{{topic.title}}</h4></a>
                        
                        {% if topic.description %}
                            <small>{{topic.description}}</small>
                        {% endif %}
                        
                        {% if not subtopic.is_leaf_node %}
                        
                            <ul class="subtopic-list">
                        
                            {% for subtopic in topic.get_descendants %}
                            
                                <li><a href="{% url 'topic-detail' slug=topic.slug %}">{{subtopic.title}}</a></li>
                                
                            {% endfor %}
                            
                            </ul>
                            
                        {% endif %}
                        
                    </div>
                
                {% endfor %}
                
            </div>

        {% endif %}

    {% endfor %}
    
    </div>
    
{% endblock %}