people/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    
    url(r'^edit/(?P<username>[\w.@+-]+)/$', views.EditProfile, name="edit-profile"),
    
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserProfile, name="user-profile"),
    
    
    
    
    
    ]

tinventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from tinventory.core import views as core_views
from people import views as people_views
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

urlpatterns = [
    
    url(r'^$', core_views.HomePage.as_view(), name='home'),
    
    url(r'^admin/', admin.site.urls),
    
    url(r'^transformations/', include('transformations.urls')),
    
    url(r'^resources/', include('resources.urls')),
    
    url(r'^topics/', include('topics.urls')),
    
    url(r'^users/', include('people.urls')),
    
    url(r'^login/$', auth_views.login, name='login'),
    
    url(r'^logout/$', auth_views.logout, name='logout'),
    
    url(r'^signup/$', core_views.signup, name='signup'),
    
    url(r'^feed/$', people_views.ActivityFeed.as_view(), name='activity-feed'),
    
    url(r'^leaderboard/$', people_views.Leaderboard, name='leaderboard'),
    
    url(r'^feedback/', core_views.FeedbackForm.as_view(), name='feedback'),
    
    url(r'^search/', core_views.SearchResults.as_view(), name='search'),
    
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
    url(r'^terms/accept/', core_views.MyAcceptTerms.as_view(), name='accept-terms'),
    url(r'^terms/', core_views.MyViewTerms.as_view(), name='terms'),
    
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^', include(wagtail_urls)),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

transformations/urls.py
from django.conf.urls import url
from . import views
from resources import views as resource_views

urlpatterns = [
     
     # TRANSFORMATION VIEWS
     
     url(r'^$', views.IndexView, name='index'),
     
     url(r'^(?P<slug>[\w-]+)$', views.TransformationDetail.as_view(), name='transformation-detail'),
     
     url(r'add/$', views.AddTransformation.as_view(), name='transformation-add'),
     
     url(r'edit/(?P<slug>[\w-]+)$', views.EditTransformation.as_view(), name='transformation-edit'),
     
     url(r'delete/(?P<pk>\d+)$', views.DeleteTransformation.as_view(), name='transformation-delete'),
     
     url(r'(?P<slug>[\w-]+)/add(?P<type>[a-z]+)/$', resource_views.AddResource, {'base':'transformation'}, name='transformation-add-resource'),
     
     url(r'add(?P<type>[a-z]+)/$', resource_views.AddResource, {'base':'transformation'}, name='transformation-add-topic-base'),
     
     ]
     

resources/models.py
from django.db import models
from django.core.urlresolvers import reverse
from transformations.models import Transformation
from topics.models import Topic
from django.contrib.auth.models import User
from mptt.models import TreeManyToManyField
from django.conf import settings
from autoslug import AutoSlugField
import datetime
import os
from people.models import Action
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Sum


class Resource(models.Model):
     
     CATEGORIES = (
          ('example', 'Real World Example'),
          ('template', 'Tool or Template'),
          ('reading', 'Theory, Guide, Article or Book'),
          ('lessons', 'Lessons Learned'),
     )
     
     RESOURCE_TYPES = (
          ('file', 'File'),
          ('link', 'Link'),
          ('post', 'Post'),
     )
     
     # def resourceTypeList(self):
     #      return [ ( x , x.__name__.capitalize() ) for x in self.__class__.__subclasses__()]
     
     def get_upload_path(instance, filename):
          return os.path.join('resources', datetime.date.today().strftime("%y-%m-%d"), filename)
          
     def filename(self):
        return os.path.basename(self.file.name)

     type = models.CharField('Resource Type', max_length=5, choices=RESOURCE_TYPES)
     
     title = models.CharField('Title', max_length=80)
     description = models.CharField(max_length=255, help_text='Describe the resource and how it may be useful to others.')
     slug = AutoSlugField(populate_from='title', unique=True, always_update=True)
     
     file = models.FileField("File",upload_to=get_upload_path, blank=True, null=True)
     link = models.URLField("Link", help_text="The URL (address), starting with \'http.\'", blank=True, null=True)
     post = models.TextField("Post", help_text="Type your post here.",  blank=True, null=True)
     
     category = models.CharField('Resource Category',max_length=10,choices=CATEGORIES)
     transformation = models.ForeignKey('transformations.Transformation', blank=True, null=True, related_name='resources')
     topics = TreeManyToManyField('topics.Topic', help_text="Ctrl-click to choose all that apply.", blank=True)
     
     credit = models.CharField('Credit',max_length=100,help_text='Who made or contributed to this?', blank=True, null=True)
     created_by = models.ForeignKey('auth.User', related_name='resources_created')
     date_modified = models.DateTimeField(auto_now=True)
     
     def __init__(self, *args, **kwargs):
          
          super(Resource, self).__init__(*args, **kwargs)

          if not self.__class__.__subclasses__():
               self.type = self.__class__.__name__.lower() # If there are no subclasses, call it a resource object.
               
          else:
               
               subclass = [x for x in self.__class__.__subclasses__() if x.__name__.lower() == self.type]
               
               if subclass:
                    self.__class__ = subclass[0]
               else:
                    raise TypeError("Please specify a type for this resource.") # But if there are subclasses, 'resource' won't do.
     
     def __str__(self):
          return self.title
          
     class Meta:
          ordering = ['-date_modified']
          
     def actions(self):
          return Action.objects.filter(target_id=self.pk, target_type=ContentType.objects.get_for_model(Resource))
          
     def created(self):
          return Action.objects.filter(target_id=self.pk, target_type=ContentType.objects.get_for_model(Resource), verb="added").first()
          
     def modified(self):
          return Action.objects.filter(target_id=self.pk, target_type=ContentType.objects.get_for_model(Resource), verb="updated").first()
          
     def total_stars(self):
          stars = Review.objects.filter(resource=self).aggregate(total=Sum('rating'))
          return stars['total']
          
          
     def related_objects(self):
          bases = [ x for x in self.topics.all()]
          # if self.transformation: 
          #      bases += self.transformation
          return bases
          
class ProxyManager(models.Manager):
     def get_query_set(self):
          return super(ProxyManager, self).get_query_set().filter(type=self.model.__name__.lower())

class File(Resource):
     
     objects = ProxyManager()
     
     class Meta:
          proxy = True
          
     def get_absolute_url(self):
          return reverse('view-file', kwargs={'slug': self.slug})

class Link(Resource):
     
     objects = ProxyManager()
     
     class Meta:
          proxy = True
          
     def get_absolute_url(self):
          return reverse('view-link', kwargs={'slug': self.slug})
          
class Post(Resource):
     
     objects = ProxyManager()
     
     class Meta:
          proxy = True
          
     def get_absolute_url(self):
          return reverse('view-post', kwargs={'slug': self.slug})
          
class Review(models.Model):
     
     REVIEW_DESCRIPTIONS = (
          (2,'Really Great'),
          (1,'Great'),
          (0,'Interesting'),
          )
     
     rating = models.SmallIntegerField(
          'Your Rating', 
          default=0, 
          choices=REVIEW_DESCRIPTIONS, 
          validators=[MaxValueValidator(2),MinValueValidator(0)])
     
     user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='reviews')
     resource = models.ForeignKey(Resource, related_name='reviews')
     
     review = models.TextField(blank=True,null=True, help_text='What\'s valuable about this resource?')
     date_modified = models.DateTimeField(auto_now=True)
     
     class Meta:
          unique_together = ("user", "resource")
          ordering = ['-date_modified']
     
     def description(self):
          return self.REVIEW_DESCRIPTIONS[2-self.rating][1]
          
     def __str__(self):
          stars = '*' * self.rating
          return '%s Review of %s by %s' % (stars, self.resource, self.user)
          
     def get_absolute_url(self):
          return self.resource.get_absolute_url()
     

transformations/models.py
from django.db import models
from django.core.urlresolvers import reverse
from autoslug import AutoSlugField
from people.models import Action
from django.contrib.contenttypes.models import ContentType
import os

# TAG MODELS

class Transformation_Tag(models.Model):
     name = models.CharField(max_length=20)
     
     class Meta:
          ordering = ['name']
          
     def __str__(self):
          #return 'Change to %s' % (self.name)
          return self.name

# TRANSFORMATION MODELS

class Transformation(models.Model):
     title = models.CharField("Transformation Title", max_length=100)
     ministry = models.ManyToManyField('Ministry', related_name='transformations')
     description = models.TextField("High-Level Description")
     problem = models.TextField("Core Problem", blank=True)
     specific_orgs = models.CharField("Specific Orgs", max_length=240, blank=True)
     primary_contact = models.CharField("Primary Contact", max_length=100, blank=True)
     
     CATEGORIES = (
          ('structure', 'Structure/Process'),
          ('strategy', 'Strategy/Policy'),
          ('service', 'Service Delivery'),
          ('people', 'People Development'),
          ('all', '\'All of the Above\''),
     )
     
     STATUSES = (
          ('current', 'Current'),
          ('Past', 'Past'),
     )
     
     category = models.CharField(verbose_name='Category', max_length=20, choices=CATEGORIES, blank=True)
     status = models.CharField(max_length=20, choices=STATUSES, blank=True)
     tags = models.ManyToManyField('Transformation_Tag', verbose_name='Areas of Focus', blank=True)
     archived = models.BooleanField(default=False)
     slug = AutoSlugField(populate_from='title')
     date_modified = models.DateTimeField(auto_now=True)
     
     class Meta:
          ordering = ['-date_modified']
     
     def get_absolute_url(self):
          return reverse('transformation-detail', kwargs={'slug':self.slug})
          
     def __str__(self):
          return self.title
          
     def ministries_list(self):
          #return ', '.join(map(str, self.ministry.all()))
          mins_list = [ min.abbrev for min in self.ministry.all() ]
          return ', '.join(mins_list)
          
     def type(self):
          return 'transformation'
          
     def actions(self):
          return Action.objects.filter(target_id=self.pk, target_type=ContentType.objects.get_for_model(Transformation))
          
     def created(self):
          return Action.objects.filter(target_id=self.pk, target_type=ContentType.objects.get_for_model(Transformation), verb="created").first()
          
     def modified(self):
          return Action.objects.filter(target_id=self.pk, target_type=ContentType.objects.get_for_model(Transformation), verb="updated").first()

class Ministry(models.Model):
     abbrev = models.CharField(max_length=6, unique=True)
     name = models.CharField(max_length=100)
     
     class Meta:
          ordering = ['abbrev']
          
     def __str__(self):
          return self.abbrev + ' - ' + self.name
     

people/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Profile, Action
from django.contrib.auth.models import User
from django.utils import timezone
from .forms import UserForm, ProfileForm
from django.urls import reverse
from django.contrib import messages
from .helpers import create_action
from django.views import generic
from django.conf import settings
from django.db.models import Sum, Count, Avg
from resources.models import Resource, Review
from django.contrib.auth import get_user_model
from transformations.models import Transformation, Ministry

def UserProfile(request, username):
    
    this_user = get_object_or_404(User, username=username)
    
    try:
        my_profile = Profile.objects.get(user=this_user)
        
    except:
        new_profile = Profile.objects.create(user=this_user)
        new_profile.last_login = timezone.now()
        new_profile.date_joined = timezone.now()
        new_profile.save()
    
    return render(request, 'people/profile.html', {'user':this_user})
    
def EditProfile(request, username):
    
    this_user = get_object_or_404(User, username=username)
    
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=this_user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=this_user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request,'Your profile has been updated.')
            create_action(request.user, 'updated', Profile.objects.get(user=this_user))
            return redirect(reverse('user-profile', kwargs={'username':username}))
            
    else:
        
        user_form = UserForm(instance=this_user)
        profile_form = ProfileForm(instance=this_user.profile)
        context = {
            'user':this_user,
            'user_form':user_form,
            'profile_form':profile_form,
            }
    
    return render(request,'people/edit_profile.html', context)
    
class ActivityFeed(generic.ListView):
    model=Action
    template_name='people/activity_feed.html'
    
class Standings(object):
    
    def __init__(self,title,xaxis,measure,queryset=None, model=None, func=None, measure_var=None):
        self.title=title
        self.xaxis=xaxis
        self.measure=measure
        self.queryset = model.objects.annotate(number=func(measure_var)).filter(number__gt=0).order_by('-number')[:5]

def Leaderboard(request):
    
    User = get_user_model()
    
    leaderboards = [
        
        Standings(
            title='Most Active Users',
            xaxis='User',
            measure='Actions',
            model=User,
            func=Count,
            measure_var='actions'
            ),
                        
        Standings(
            title='Users with most Stars',
            xaxis='User',
            measure='Stars',
            model=User,
            func=Sum,
            measure_var='resources_created__reviews__rating'
            ),
        
        Standings(
            title='Top Resources',
            xaxis='Resource',
            measure='Stars',
            model=Resource,
            func=Sum,
            measure_var='reviews__rating'
            ),
            
        Standings(
            title='Highest Avg Rating',
            xaxis='Resource',
            measure='Stars',
            model=Resource,
            func=Avg,
            measure_var='reviews__rating'
            ),
                    
        Standings(
            title='Top Reviewers',
            xaxis='User',
            measure='Reviews',
            model=User,
            func=Count,
            measure_var='reviews'
            ),
            
        Standings(
            title='Transformations with Most Resources',
            xaxis='Transformation',
            measure='Resources',
            model=Transformation,
            func=Count,
            measure_var='resources'
            ),
            
        Standings(
            title='Ministry with most Transformations',
            xaxis='Ministry',
            measure='Transformations',
            model=Ministry,
            func=Count,
            measure_var='transformations'
            ),
            
        Standings(
            title='Ministry with most Users',
            xaxis='Ministry',
            measure='Users',
            model=Ministry,
            func=Count,
            measure_var='profiles'
            ),
    ]
    
    context = {'leaderboards':leaderboards}
    
    return render(request,'people/leaderboard.html',context)
    

tinventory/templates/transformations/index.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}

{% block header %}Transformations{% endblock %}

{% block item-buttons %}
    <a href="{% url 'transformation-add' %}" class="button-flex">Add Transformation</a>
{% endblock %}

{% block content %}

     <div class="row form-group">
          
          <form action="" method="GET">
               {% for field in t_filter_form %}
                    <div class="col-md-2">
                         <h5>{{ field.label }}</h5>
                         {{ field|add_class:"form-control"}} 
                    </div>
               {% endfor %}
               
               <div class="col-md-4 align-bottom btn-group">
                    <h5 class="invisible">Buttons</h5> <!-- pushes the buttons down for appearances -->
                    <button class="btn btn-default text-right" type="submit" ><span class="glyphicon glyphicon-filter"></span> Filter</button>
                    </form> <!-- end the first form here -->
                    
                    <!-- second form to indicate the form should be cleared -->
                    <form action="" method="GET"> 
                         <button class="btn btn-default text-right" value="Clear" type="submit">
                         <span class="glyphicon glyphicon-sunglasses"></span> Clear</button>
                    </form>
               </div>
          
     </div>
     
     <div class="row">
          <div class="col-md-12">
               <table class="table table-striped table-hover table-responsive align-middle col-md-12">
                    <tbody>
                    <tr>
                         <th>Ministry</th>
                         <th>Title</th>
                         <th>Category</th>
                         <!--<th>Areas of Focus</th>-->
                         <th>Past/Current</th>
                    </tr>
                    {% for transformation in transformation_list %}
                    <tr>
                         <td>{{ transformation.ministries_list}}</td>
                         <td><a href="{% url 'transformation-detail' transformation.slug %}" class="">{{ transformation.title|truncatewords:12 }}</a></td>
                         <td>{{ transformation.get_category_display }}</td>
                         <!--<td>
                              {{ transformation.tags.all|join:", " }}
                         </td>-->
                         <td>{{ transformation.get_status_display }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
               </table>
          </div>
     </div>

{% endblock %}

tinventory/templates/transformations/resource_detail.html
{% extends "base.html" %}

{% block title %} 
     {{object.type}} - {{object.title}}
{% endblock %}

{% block header %}
     {{object.title}}<small> ({{ object.type }})</small>
     
     <div class="pull-right"> <!-- Edit & delete buttons -->
          
          <a class="btn btn-default" href=
               "{% if object.type == 'Link' %}{% url 'edit-link' object.pk %}{% endif %}
               {% if object.type == 'File' %}{% url 'edit-file' object.pk %}{% endif %}"
               data-toggle="tooltip" title="Edit">
               
               <span class="glyphicon glyphicon-pencil"></span>
          </a>
          
          <a class="btn btn-default" href=
               "{% if object.type == 'Link' %}{% url 'delete-link' object.pk %}{% endif %}
               {% if object.type == 'File' %}{% url 'delete-file' object.pk %}{% endif %}"
               data-toggle="tooltip" title="Delete">
               
               <span class="glyphicon glyphicon-trash"></span>
          </a>

     </div>
     
     

{% endblock %}

{% block content %}

     <h3>Details:</h3>
     <div class="row">
          <div class="col-md-12">
               <table class="table table-striped align-middle">
                    <tr>
                         <th class="col-md-2">{{object.type}}</th>
                         <td class="col-md-10">
                              {%if object.type == 'Link' %}
                                   <a href="{{object.resource}}">{{object.resource}}</a>
                              {% endif %}
                              {%if object.type == 'File' %}
                                   <a href="/media/{{ object.resource }}">{{object.filename}}</a>
                              {% endif %}
                         </td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Title</th>
                         <td class="col-md-10 strong">{{object.title}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Description</th>
                         <td class="col-md-10">{{object.description}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Transformation</th>
                         <td class="col-md-10">
                              <a href="{% url 'transformation-detail' object.transformation.pk %}">
                                   {{object.transformation}}
                              </a>
                         </td>
                    </tr>                    
                    <tr>
                         <th class="col-md-2">Tags</th>
                         <td class="col-md-10">{{object.tags.all|join:', '}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Date</th>
                         <td class="col-md-10">{{object.date_modified}}</td>
                    </tr>

               </table>
               
          </div>
     </div>

{% endblock %}

tinventory/templates/transformations/resource_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Add {{form.resource.label}}{% endblock %}
{% block header %}Add {{form.resource.label}}{% endblock %}

{% block content %}
{% include 'transformations/form_table_layout.html' %}
{% endblock %}

tinventory/templates/transformations/resources.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block header %}Resources

     <!--<div class="pull-right">-->
     <!--     <a class="btn btn-success" href="{% url 'transformation-add' %}" data-toggle="tooltip" title="New Transformation">-->
     <!--          <span class="glyphicon glyphicon-plus-sign"></span>  Add New Transformation-->
     <!--     </a>-->
     <!--</div>-->

{% endblock %}

{% block content %}
     
     <div class="row">
          <div class="col-md-12">
               <table class="table table-striped table-hover table-responsive align-middle col-md-12">
                    <tbody>
                    <tr>
                         <th>Type</th>
                         <th>Resource</th>
                         <th>Transformation</th>
                         <th>Tags</th>
                    </tr>
                    {% for resource in resources %}
                    <tr>
                         <td>
                              {% if resource.type == 'Link' %}<span class="glyphicon glyphicon-link large"></span>
                              {% elif resource.type == 'File' %}<span class="glyphicon glyphicon-file large"></span>{% endif %}
                         </td>
                         <td>
                              {% if resource.type == 'Link' %}
                                   <a href="{% url 'view-link' resource.pk %}">
                              {% elif resource.type == 'File' %}
                                   <a href="{% url 'view-file' resource.pk %}">
                              {% endif %}
                              <span class="strong">{{resource.title}}</span></a>
                              <br>
                              {{resource.description}}
                         </td>
                         <td><a href="{% url 'transformation-detail' resource.transformation.pk %}">{{ resource.transformation }}</td></a>
                         <td>{{ resource.tag_list }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
               </table>
          </div>
     </div>

{% endblock %}

tinventory/templates/transformations/transformation_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}
{% block header %}Confirm Delete{% endblock %}

{% block content %}
<div class="panel panel-danger">
    <div class="panel-heading">Are you sure you want to delete <strong>"{{ object }}"</strong>?</div>
    <div class="panel-body">
        <form action="" method="post">
            {% csrf_token %}
            <button class="btn btn-large btn-danger" type="submit" value="Delete" />Delete</button>
            <a class="btn btn-large btn-default" href="{% url 'transformation-detail' object.pk %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

tinventory/templates/transformations/transformation_detail.html
{% extends "core/base_page.html" %}
{% load humanize %}

{% block title %} 
     Transformation Inventory - {{transformation.title}}
{% endblock %}

{% block header %}
     {{transformation.title|truncatewords:10}}<small> ({{ transformation.ministries_list }})</small>
{% endblock %}

{% block item-buttons %}
    <a href="{% url 'transformation-delete' transformation.pk %}" class="button-flex-white">Delete Transformation</a>
{% endblock %}

{% block content %}

     <div class="row">
          <div class="col-md-8">
               <h3>Details:
               
                    <div class="pull-right">
                         <a class="btn btn-default" href="{% url 'transformation-edit' transformation.slug %}" data-toggle="tooltip" title="Edit Details">
                              <span class="glyphicon glyphicon-pencil"></span> Edit
                         </a>
                    </div>
                    
               </h3>
               
               <table class="table table-striped align-middle">
                    <tr>
                         <th class="col-md-3">Transformation Title</th>
                         <td class="col-md-9">{{transformation.title}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Ministry</th>
                         <td class="col-md-10">{{transformation.ministries_list}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Specific Orgs</th>
                         <td class="col-md-10">{{transformation.specific_orgs}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">High-Level Description</th>
                         <td class="col-md-10">{{transformation.description|linebreaks}}</td>
                    </tr>                    
                    <tr>
                         <th class="col-md-2">What Problem is it Addressing?</th>
                         <td class="col-md-10">{{transformation.problem|linebreaks}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Primary Category</th>
                         <td class="col-md-10">{{transformation.get_category_display}}</td>
                    </tr>
                    <!--<tr>
                         <th class="col-md-2">Areas of Focus</th>
                         <td class="col-md-10">{{transformation.tags.all|join:', '}}</td>
                    </tr>-->
                    <tr>
                         <th class="col-md-2">Status</th>
                         <td class="col-md-10">{{transformation.get_status_display}}</td>
                    </tr>
                    <tr>
                         <th class="col-md-2">Primary Contact</th>
                         <td class="col-md-10">{{transformation.primary_contact}}</td>
                    </tr>
                    {% with transformation.created as created %}{% if created %}
                    <tr>
                         <th>Created</th>
                         <td>{{created.created|naturalday|capfirst}} by <a href="{{created.user.profile.get_absolute_url}}">{{created.user.get_full_name|title}}</a>.</td>
                    </tr>
                    {% endif %}{% endwith %}
                    {% with transformation.modified as modified %}{% if modified %}
                    <tr>
                         <th>Last Modified</th>
                         <td>{{modified.created|naturalday|capfirst}} by <a href="{{modified.user.profile.get_absolute_url}}">{{modified.user.get_full_name|title}}</a>.</td>
                    </tr>
                    {% endif %}{% endwith %}

               </table>
               
          </div>
          
          <div class="col-md-4">
               
               <h3>Related Resources:
               
               <div class="pull-right dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-plus-sign"></span>  Add
                  <span class="caret"></span></button>
                   
                  <ul class="dropdown-menu">
                      <li><a href="{% url 'transformation-add-resource' type='link' slug=transformation.slug %}">Add a new link</a></li>
                      <li><a href="{% url 'transformation-add-resource' type='file' slug=transformation.slug %}">Add a new file</a></li>
                      <li><a href="{% url 'transformation-add-resource' type='post' slug=transformation.slug %}">Add a new post</a></li>
                  </ul>
               </div>
     
               </h3>
     
               {% include 'resources/resource_list_include.html' with resource_list=transformation.resources.all %}
               
          </div>
     </div>

{% endblock %}

tinventory/templates/transformations/transformation_form.html
{% extends "core/base_page.html" %}
{% load widget_tweaks %}

{% block title %}{% if object %}Edit{% else %}Add{% endif %} Transformation{% endblock %}
{% block header %}{% if object %}Edit{% else %}Add{% endif %} Transformation{% endblock %}

{% block content %}

{% include 'core/form_table_layout.html' %}
               
{% endblock %}